// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoxZTvGhhE0QlAygI7avUzCUDPWY8xX-o',
    appId: '1:502657329067:web:4fda7677e8bd62e2ae14ee',
    messagingSenderId: '502657329067',
    projectId: 'wellness-app-8fc44',
    authDomain: 'wellness-app-8fc44.firebaseapp.com',
    storageBucket: 'wellness-app-8fc44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG73iXEvAGznGkRm7DyO4cnF4Eb7P2g6Y',
    appId: '1:502657329067:android:7c82cc90f877caabae14ee',
    messagingSenderId: '502657329067',
    projectId: 'wellness-app-8fc44',
    storageBucket: 'wellness-app-8fc44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfQN62mwlSInAYh-teezcT5C56bQEeZYg',
    appId: '1:502657329067:ios:990ebf46bea5c95cae14ee',
    messagingSenderId: '502657329067',
    projectId: 'wellness-app-8fc44',
    storageBucket: 'wellness-app-8fc44.firebasestorage.app',
    iosBundleId: 'com.example.wellnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfQN62mwlSInAYh-teezcT5C56bQEeZYg',
    appId: '1:502657329067:ios:990ebf46bea5c95cae14ee',
    messagingSenderId: '502657329067',
    projectId: 'wellness-app-8fc44',
    storageBucket: 'wellness-app-8fc44.firebasestorage.app',
    iosBundleId: 'com.example.wellnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoxZTvGhhE0QlAygI7avUzCUDPWY8xX-o',
    appId: '1:502657329067:web:d262343cc87e665fae14ee',
    messagingSenderId: '502657329067',
    projectId: 'wellness-app-8fc44',
    authDomain: 'wellness-app-8fc44.firebaseapp.com',
    storageBucket: 'wellness-app-8fc44.firebasestorage.app',
  );
}
